/**
 * PROJETOS DE EXEMPLO — para visualizar o layout da galeria.
 * Substituídos automaticamente pelos seus projetos reais via /admin.
 */

export const SAMPLE_PROJECTS = [
  {
    id: 1,
    slug: "identidade-aurora",
    title: "Aurora",
    subtitle: "Identidade para marca de wellness premium",
    category: "branding",
    client: "Aurora Studio",
    year: "2024",
    location: "São Paulo",
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1400&q=90&auto=format",
    color: "#C9A56C",
    description: "Construção de identidade visual completa para marca de wellness. Sistema tipográfico autoral, paleta mineral e direção de fotografia.",
    isDraft: false,
    featured: true,
    stills: [],
    credits: [],
    awards: [],
    tags: ["branding", "identity", "wellness"],
    seoTitle: "", seoDescription: "", seoOgImage: "",
    headline: "", subheadline: "", mainVideo: "",
    context: "", concept: "", direction: "", challenge: "", solution: "", result: "",
    duration: "", format: "",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: 2,
    slug: "motion-fragmento",
    title: "Fragmento",
    subtitle: "Film de marca para festival de design",
    category: "motion",
    client: "Festival D",
    year: "2024",
    location: "Rio de Janeiro",
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1400&q=90&auto=format",
    color: "#8B8580",
    description: "Direção de um curta institucional de 2 minutos. Conceito visual baseado em decomposição tipográfica e reconstrução de identidade.",
    isDraft: false,
    featured: false,
    stills: [],
    credits: [],
    awards: [],
    tags: ["motion", "film", "branding"],
    seoTitle: "", seoDescription: "", seoOgImage: "",
    headline: "", subheadline: "", mainVideo: "",
    context: "", concept: "", direction: "", challenge: "", solution: "", result: "",
    duration: "2 min", format: "16:9 / Vertical",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: 3,
    slug: "editorial-forma",
    title: "Forma",
    subtitle: "Design editorial para publicação independente",
    category: "identidade",
    client: "Revista Forma",
    year: "2023",
    location: "São Paulo",
    coverImage: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=1400&q=90&auto=format",
    color: "#F5F2EC",
    description: "Sistema editorial completo para publicação independente de design e arquitetura. Grade tipográfica, sistema de cores e templates.",
    isDraft: false,
    featured: false,
    stills: [],
    credits: [],
    awards: [],
    tags: ["editorial", "typography", "print"],
    seoTitle: "", seoDescription: "", seoOgImage: "",
    headline: "", subheadline: "", mainVideo: "",
    context: "", concept: "", direction: "", challenge: "", solution: "", result: "",
    duration: "", format: "A4 / Digital",
    createdAt: new Date("2023-11-01"),
    updatedAt: new Date("2023-11-01"),
  },
];
