/**
 * PROJETOS DE EXEMPLO — para visualizar o layout da galeria e da página de detalhe.
 * Substituídos automaticamente pelos seus projetos reais via /admin.
 *
 * Categorias de imagem (still.type):
 *   "identidade" — paleta, texturas, moodboard visual
 *   "logo"       — construção e variações do logotipo
 *   "site"       — telas e interfaces digitais
 *   "sistema"    — aplicações, papelaria, elementos do sistema
 */

export const SAMPLE_PROJECTS = [
  {
    id: 1,
    slug: "identidade-aurora",
    title: "Aurora",
    subtitle: "Identidade para marca de wellness premium",
    category: "branding",
    client: "Aurora Studio",
    year: "2024",
    location: "São Paulo",
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1600&q=90&auto=format",
    color: "#C9A56C",
    headline: "Aurora",
    subheadline: "Uma identidade construída sobre luz, silêncio e proporção.",
    description: "Construção de identidade visual completa para marca de wellness. Sistema tipográfico autoral, paleta mineral e direção de fotografia.",
    context: "A Aurora chegou até nós sem nome fixado — apenas a intenção de criar um espaço de bem-estar que não parecesse clínico nem espiritual demais. O desafio era encontrar o meio-termo: sofisticação sem frieza.",
    concept: "A ideia central nasceu da observação de como a luz do amanhecer muda de temperatura ao longo de poucos minutos — de fria a quente, de azul a dourada. Construímos o sistema cromático inteiro sobre esse gradiente natural, e o logotipo é literalmente a curva desse nascer do sol, reduzida a uma linha.",
    challenge: "Marcas de wellness tendem para dois extremos: clínico e distante, ou espiritual e vago. A Aurora precisava ocupar o espaço raro entre os dois — precisão com calor humano.",
    solution: "Um sistema tipográfico com uma serifa contemporânea para títulos (transmite autoridade sem ser fria) combinada com uma sans-serif geométrica para textos operacionais. A paleta migra do dourado ao violeta conforme o contexto de uso — manhã, tarde, noite.",
    result: "O sistema foi aplicado em identidade completa, site institucional e sistema de sinalização física do espaço físico da marca.",
    isDraft: false,
    featured: true,
    stills: [
      { url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=90&auto=format", type: "identidade", order: 0 },
      { url: "https://images.unsplash.com/photo-1618172193622-ae2d025f4032?w=1200&q=90&auto=format", type: "identidade", order: 1 },
      { url: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1200&q=90&auto=format", type: "logo", order: 0 },
      { url: "https://images.unsplash.com/photo-1620121692029-d088224ddc74?w=1200&q=90&auto=format", type: "logo", order: 1 },
      { url: "https://images.unsplash.com/photo-1522542550221-31fd19575a2d?w=1200&q=90&auto=format", type: "site", order: 0 },
      { url: "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=1200&q=90&auto=format", type: "site", order: 1 },
      { url: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=1200&q=90&auto=format", type: "sistema", order: 0 },
      { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=90&auto=format", type: "sistema", order: 1 },
    ],
    credits: [
      { role: "Direção Criativa", name: "Lucas Domingues" },
      { role: "Type Design", name: "Lucas Domingues" },
    ],
    awards: [],
    tags: ["branding", "identity", "wellness"],
    seoTitle: "", seoDescription: "", seoOgImage: "",
    mainVideo: "",
    direction: "",
    duration: "", format: "Identidade Completa · Site · Sinalização",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: 2,
    slug: "motion-fragmento",
    title: "Fragmento",
    subtitle: "Film de marca para festival de design",
    category: "motion",
    client: "Festival D",
    year: "2024",
    location: "Rio de Janeiro",
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=90&auto=format",
    color: "#8B8580",
    headline: "Fragmento",
    subheadline: "A identidade de um festival contada através da decomposição.",
    description: "Direção de um curta institucional de 2 minutos. Conceito visual baseado em decomposição tipográfica e reconstrução de identidade.",
    context: "O Festival D precisava de um filme de abertura que comunicasse sua essência em 2 minutos: um evento sobre fragmentação e recombinação de ideias em design.",
    concept: "Cada letra do logotipo do festival se fragmenta em partículas geométricas no início do filme, viaja pela tela seguindo trajetórias inspiradas em sistemas de partículas, e se recombina no final formando uma nova composição tipográfica a cada edição do festival.",
    challenge: "Comunicar um conceito abstrato — fragmentação criativa — sem cair em clichês visuais de 'partículas voando' genéricos que já existem em milhares de motion reels.",
    solution: "Construímos um sistema de física real (não apenas keyframes) onde cada fragmento respeita massa, gravidade e colisão. O resultado tem imprevisibilidade orgânica que motion puramente animado não teria.",
    result: "O filme abriu as 3 edições seguintes do festival, cada uma com uma recombinação tipográfica diferente gerada pelo mesmo sistema.",
    isDraft: false,
    featured: false,
    stills: [
      { url: "https://images.unsplash.com/photo-1620121692029-d088224ddc74?w=1200&q=90&auto=format", type: "identidade", order: 0 },
      { url: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=1200&q=90&auto=format", type: "identidade", order: 1 },
      { url: "https://images.unsplash.com/photo-1618172193622-ae2d025f4032?w=1200&q=90&auto=format", type: "logo", order: 0 },
      { url: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1200&q=90&auto=format", type: "sistema", order: 0 },
    ],
    credits: [
      { role: "Direção Criativa", name: "Lucas Domingues" },
      { role: "Motion Design", name: "Lucas Domingues" },
    ],
    awards: [],
    tags: ["motion", "film", "branding"],
    seoTitle: "", seoDescription: "", seoOgImage: "",
    mainVideo: "",
    direction: "",
    duration: "2 min", format: "16:9 / Vertical",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: 3,
    slug: "editorial-forma",
    title: "Forma",
    subtitle: "Design editorial para publicação independente",
    category: "identidade",
    client: "Revista Forma",
    year: "2023",
    location: "São Paulo",
    coverImage: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=1600&q=90&auto=format",
    color: "#F5F2EC",
    headline: "Forma",
    subheadline: "Sistema editorial para uma publicação sobre arquitetura e design.",
    description: "Sistema editorial completo para publicação independente de design e arquitetura. Grade tipográfica, sistema de cores e templates.",
    context: "A Revista Forma nasceu como projeto independente de dois arquitetos que queriam uma publicação sem a estética corporativa das revistas de design tradicionais.",
    concept: "Baseamos toda a grade editorial no sistema modular de Josef Müller-Brockmann, mas quebramos a rigidez suíça introduzindo uma segunda grade rotacionada em 3 graus — um desvio quase imperceptível que dá à publicação uma tensão visual sutil, como se a página nunca estivesse perfeitamente alinhada.",
    challenge: "Criar uma identidade editorial que respeitasse a tradição do design suíço (que o público de arquitetura reconhece e valoriza) sem parecer uma cópia nostálgica.",
    solution: "Grid modular de 12 colunas com o desvio de 3° mencionado, tipografia Neue Haas Grotesk para textos e uma serifa condensada autoral para títulos de matérias.",
    result: "3 edições publicadas, distribuição em livrarias de arquitetura de São Paulo e Rio de Janeiro.",
    isDraft: false,
    featured: false,
    stills: [
      { url: "https://images.unsplash.com/photo-1483058712412-4245e9b90334?w=1200&q=90&auto=format", type: "identidade", order: 0 },
      { url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1200&q=90&auto=format", type: "sistema", order: 0 },
      { url: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=1200&q=90&auto=format", type: "sistema", order: 1 },
    ],
    credits: [
      { role: "Direção de Arte", name: "Lucas Domingues" },
      { role: "Design Editorial", name: "Lucas Domingues" },
    ],
    awards: [],
    tags: ["editorial", "typography", "print"],
    seoTitle: "", seoDescription: "", seoOgImage: "",
    mainVideo: "",
    direction: "",
    duration: "", format: "A4 / Digital",
    createdAt: new Date("2023-11-01"),
    updatedAt: new Date("2023-11-01"),
  },
];
